#!/bin/bash
#
# Kehamassi indeks
#
echo -n "Sisesta ees- ja perenimi: "
read eesnimi perenimi
echo -n "Sisesta pikkus(m): "
read  pikkus
echo -n "Sisesta kaal (kg): "
read mass

#Kontrollime kas sisestatus väärtus on tühi
if [ -n "$mass" ] && [ -n "$pikkus" ]; then 
kmi=$(echo "scale=2;$mass / ($pikkus^2)" | bc)
echo "Lugupeetud $perenimi $eesnimi"
echo "Sinu kehamassi indeks = $kmi"

# erinevad väljundid
alakaal_t=$(echo "$kmi < 19" | bc)
normaal_t=$(echo "$kmi >= 19 && $kmi < 25" | bc)
ulekaal_t=$(echo "$kmi >=25 && $kmi < 30" | bc)
rasvumine_t=$(echo "$kmi >=30" | bc)
# alakaal
if [ $alakaal_t -eq 1 ]; then
  echo "ALAKAAL"
  echo "Alakaal iseenesest ei ole tervisele ohtlik."
  echo "Kuid toitainete puudus võib põhjustada ohtliku terviserikke."
# normaalkaal
elif [ $normaal_t -eq 1 ]; then
  echo "NORMAALKAAL"
  echo "Te näete võrratu välja :) "
# ülekaal
elif [ $ulekaal_t -eq 1 ]; then
  echo "ÜLEKAAL"
  echo "See võiks juba olla ohtlik"
# rasvumine
elif [ $rasvumine_t -eq 1 ]; then
  echo "RASVUMINE"
  echo "Tuleb midagi ettevõtta - elule ohtlik"
else
  echo "Probleem skripti kasutamisega"
fi
else
echo "Mass ja pikkus peavad olema väärtustatud"
fi
