#! /bin/bash
#
# Kasutaja tervitus
#
# Skripti algus
#
# echo "Tere User!"
echo -n "Tere "
echo -n `whoami | cut -c1 | tr [:lower:] [:upper:]` #lõike esimene täht ja muuda suureks
echo -n `whoami | cut -c2-`  #lõika kõik tähed alatest 2-st
echo  "!"
#
# skiprti lõpp
